### ISSUE TITLE
jss-nested conflict

### ISSUE THREAD

**Issue by oliviertassinari** [cssinjs/jss-global#4]
Using the following rule is raising at that [line](https://github.com/cssinjs/jss-nested/blob/master/src/index.js#L25) as the `GlobalContainerRule` do not implement the `getRule` method as the `StyleSheet` [one](https://github.com/cssinjs/jss/blob/master/src/StyleSheet.js#L133).

```js
{
  '@global': {
    html: {
      background: '#eee',
       '@media (max-width: 767px)': {
         userSelect: 'none',
      },
    },
  },
}
```

**Comment by kof** [comment]
Seems to be similar to https://github.com/cssinjs/jss/issues/381 but I will add a test for this case as well.

**Comment by kof** [comment]
Issue moved to [cssinjs/jss #387](https://github.com/cssinjs/jss/issues/387) via [**ZenHub**](https://www.zenhub.com/)
